const state = {
	steps: [
        {
            shorthand: 'Sterilization reminder',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Before we get started, remember that good sterilization is crucial! Make sure to spray your hands with 70% ethanol often! You should do this each time you bring your hands in or out of the bio hood.',
            subProtocol: 'TBD',
            spokenPrompt: 'Before we get started, remember that good sterilization is crucial! Make sure to spray your hands with 70% ethanol often! You should do this each time you bring your hands in or out of the bio hood.',
        },
        {
            shorthand: 'Prepare materials',
            stepComplete: false,
            displayedText: 'Prepare your materials. Take the trypsin out of the freezer, and the cell media out of the refrigerator and warm them in a 37°C water bath',
            subProtocol: 'TBD',
            spokenPrompt: 'Now, let\'s prepare your materials. Take the trypsin out of the freezer, and the cell media out of the refrigerator and warm them in a 37 degree Celsius water bath',
            followUpAction: null,
        },
        {
            shorthand: 'Sterilize microscope',
            stepComplete: false,
            displayedText: 'Wipe the microscope stage with a kim wipe sprayed with 70% ethanol.',
            subProtocol: 'TBD',
            spokenPrompt: 'Wipe the microscope stage with a kim wipe sprayed with 70% ethanol.',
            followUpAction: null,
        },
        {
            shorthand: 'Sterilize incubator and hands, and take cells out of the incubator',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Spray your hands, the outside of the incubator main door, and the glass door with 70% ethanol. Then, take the cell culture flask out of the incubator, and place it on the microscope stage.',
            subProtocol: 'TBD',
            spokenPrompt: 'Spray your hands, the outside of the incubator main door, and the glass door with 70% ethanol. Then, take the cell culture flask out of the incubator, and place it on the microscope stage. ',
        },
        {
            shorthand: 'Prepare the microscope',
            stepComplete: false,
            displayedText: 'Turn on the microscope and set the magnification to 4x.',
            subProtocol: 'TBD',
            spokenPrompt: 'Turn on the microscope and set the magnification to 4x.',
            followUpAction: null,
        },
        {
            shorthand: 'View cells under microscope',
            stepComplete: false,
            displayedText: 'Adjust the position and focus until you can see the cells clearly.',
            subProtocol: 'TBD',
            spokenPrompt: 'Adjust the position and focus until you can see the cells clearly.',
            followUpAction: null,
        },
        {
            shorthand: 'Check confluency',
            stepComplete: false,
            followUpAction: 'checkConfluency',
            displayedText: 'Now, let\'s figure out what the confluency of your cells is. Confluency represents the percentage of the flask that\'s covered by cells overall. You might have to move the plate around a bit to get a sense for how much is covered.',
            subProtocol: 'TBD',
            spokenPrompt: 'Now, let\'s figure out what the confluency of your cells is. Confluency represents the percentage of the flask that\'s covered by cells overall. You might have to move the plate around a bit to get a sense for how much is covered.',
        },
        {
            shorthand: 'Take images of cells at 4x',
            stepComplete: false,
            spokenPrompt: 'To document how the cells are growing, let\'s take a few images with the microscope. First, take a look at the screen for how to set the filename. Once you\'ve adjusted the filename, let me know.',
            subProtocol: 'TBD',
            displayedText: 'Take a images of the cells at 4x confluency. You\'ll first need to adjust the filename to match the naming convention. Once you\'ve adjusted the filename, say "What\'s next".',
            followUpAction: null,
        },
        {
            shorthand: 'Take images of cells at 10x',
            stepComplete: false,
            displayedText: 'Now, switch the magnification to 10x, and fix the focus if necessary. Take four images at this magnification, moving the plate around between each image to capture a new portion of the flask. Remember, you\'ll also need to change the filename.',
            subProtocol: 'TBD',
            spokenPrompt: 'Now, switch the magnification to 10x, and fix the focus if necessary. Take four images at this magnification, moving the plate around between each image to capture a new portion of the flask.',
            followUpAction: null,
        },
        {
            shorthand: 'Turn off the microscope light',
            stepComplete: false,
            displayedText: 'Turn off the microscope light',
            subProtocol: 'TBD',
            spokenPrompt: 'Now that we\'re done looking at the cells for now, turn off the microscope light.',
            followUpAction: null,
        },
        {
            shorthand: 'Get ready to bring your cells into the hood',
            stepComplete: false,
            displayedText: 'Turn on the hood light and fan, and then spray the outside and inside the biocabinet with 70% ethanol. Turn on the aspirator pump.',
            subProtocol: 'TBD',
            spokenPrompt: 'Turn on the hood light and fan, and then spray the outside and inside the biocabinet with 70% ethanol. Turn on the aspirator pump.',
            followUpAction: null,
        },
        {
            shorthand: 'Bring sterilized trypsin and media into hood',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Spray the outside of the containers of the trypsin and cell media with 70% ethanol. Put them both into the hood. ',
            subProtocol: 'TBD',
            spokenPrompt: 'Spray the outside of the containers of the trypsin and cell media with 70% ethanol. Put them both into the hood. ',
        },
        {
            shorthand: 'Bring sterilized culture flask into hood',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Wipe the culture flask with a kim wipe sprayed with 70% ethanol, and move the flask into the bio cabinet.',
            subProtocol: 'TBD',
            spokenPrompt: 'Wipe the culture flask with a kim wipe sprayed with 70% ethanol, and move the flask into the bio cabinet.',
        },
        {
            shorthand: 'Prepare to aspirate',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Connect a glass pipette tip to the aspirator tube.',
            subProtocol: 'TBD',
            spokenPrompt: 'Connect a glass pypette tip to the aspirator tube.',
        },
        {
            shorthand: 'Aspirate media',
            stepComplete: false,
            displayedText: 'Tilt the culture flask and aspirate the media inside from the bottom corner of the flask. Be sure not to let the pipette tip touch the surface of the culture flask - the cells are attached to this surface.',
            subProtocol: 'TBD',
            spokenPrompt: 'Tilt the culture flask and aspirate the media inside from the bottom corner of the flask. Be sure not to let the pypette tip touch the surface of the culture flask - the cells are attached to this surface.',
            followUpAction: null,
        },
        {
            shorthand: 'Wash cells with PBS',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Wash the cells with 2-3 mL of PBS, and then aspirate the PBS.',
            subProtocol: 'TBD',
            spokenPrompt: 'Wash the cells with 2 to 3 <sub alias=\'milliliters\'>mL</sub> of PBS, and then aspirate the PBS.',
        },
        {
            shorthand: 'Add trypsin to flask',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Add 2 mL of trypsin. This should cover the surface of the flask.',
            subProtocol: 'TBD',
            spokenPrompt: 'Add 2 <sub alias=\'milliliters\'>mL</sub> of trypsin. This should cover the surface of the flask.',
        },
        {
            shorthand: 'Incubate cells',
            stepComplete: false,
            displayedText: 'Place the cells in the incubator for 5 minutes.',
            subProtocol: 'TBD',
            spokenPrompt: 'Place the cells in the incubator for 5 minutes.',
            followUpAction: 'placeCellsInIncubator',
        },
        {
            shorthand: 'Upload images to database',
            stepComplete: false,
            displayedText: 'While you\'re waiting for your cells, upload the images you took earlier to the database.',
            subProtocol: 'TBD',
            spokenPrompt: 'While you\'re waiting for your cells, upload the images you took earlier to the database.',
            followUpAction: 'uploadCellsToDatabase',
        },
        {
            shorthand: 'Remove cells from incubator',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Remove the cells from incubator and tap the container gently to remove any cells that might still be attached to its surface.',
            subProtocol: 'TBD',
            spokenPrompt: 'Remove the cells from incubator and tap the container gently to remove any cells that might still be attached to its surface.',
        },
        {
            shorthand: 'Observe trypsinized cells under microscope',
            stepComplete: false,
            displayedText: 'Observe the cells in the flask under the microscope to make sure that all the cells have been detached from the surface. Detached cells should look balled-up and will be floating around in the solution.',
            subProtocol: 'TBD',
            spokenPrompt: 'Observe the cells in the flask under the microscope to make sure that all the cells have been detached from the surface. Detached cells should look balled-up and will be floating around in the solution.',
            followUpAction: null,
        },
        {
            shorthand: 'Neutralize trypsin and mix cells',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Add 2 mL of media and gently mix it with a pipette to neutralize the trypsin. This should result in a 1 to 1 ratio of media and trypsin in the flask.',
            subProtocol: 'TBD',
            spokenPrompt: 'Add 2 <sub alias=\'milliliters\'>mL</sub> of media and gently mix it with a pypette to neutralize the trypsin. This should result in a 1 to 1 ratio of media and trypsin in the flask.',
        },
        {
            shorthand: 'Place cells in centrifuge tube',
            stepComplete: false,
            displayedText: 'Place the cells and media into a 15 mL centrifuge tube - there should be about 4 mL of solution.',
            subProtocol: 'TBD',
            spokenPrompt: 'Place the cells and media into a 15 <sub alias=\'milliliters\'>mL</sub> centrifuge tube - there should be about 4 <sub alias=\'milliliters\'>mL</sub> of solution.',
            followUpAction: null,
        },
        {
            shorthand: 'Centrifuge cells',
            stepComplete: false,
            followUpAction: 'placeCellsInCentrifuge',
            displayedText: 'Centrifuge the solution at 200G(RCF) for 10 minutes. I\'ll set a timer for 10 minutes.',
            subProtocol: 'TBD',
            spokenPrompt: 'Centrifuge the solution at 200G(RCF) for 10 minutes.',
        },
        {
            shorthand: 'Label new culture flask',
            stepComplete: false,
            followUpAction: 'guideLabeling',
            displayedText: 'While the centrifuge is running, let\'s get some other prep work taken care of. Label the cell culture flask with your initials, today\'s date, the type of cell, the passage number, and the ratio at which you\'re going to split the cells.',
            subProtocol: 'TBD',
            spokenPrompt: 'While the centrifuge is running, let\'s get some other prep work taken care of. Label the cell culture flask with your initials, today\'s date, the type of cell, the passage number, and the ratio at which you\'re going to split the cells.',
        },
        {
            shorthand: 'Add media to new flask and incubate',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Add 5 mL of media to the labeled flask and place it into the incubator.',
            subProtocol: 'TBD',
            spokenPrompt: 'Add 5 <sub alias=\'milliliters\'>mL</sub> of media to the labeled flask and place it into the incubator.',
        },
        {
            shorthand: 'Wait until the centrifuge is done running',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Sit tight while we wait until the centrifuge is done',
            subProtocol: 'TBD',
            spokenPrompt: 'Sit tight while we wait for the centrifuge to finish!',
        },
        {
            shorthand: 'Take flask with media out of incubator',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Now that the centrifuge is done, take the flask with culture media out from the incubator and place in the biocabinet..',
            subProtocol: 'TBD',
            spokenPrompt: 'Now that the centrifuge is done, take the flask with culture media out from the incubator and place in the biocabinet..',
        },
        {
            shorthand: 'Check for pellet',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Take the tube out from the centrifuge, and check whether you can see a pellet at the bottom. It might be really subtle!',
            subProtocol: 'TBD',
            spokenPrompt: 'Take the tube out from the centrifuge, and check whether you can see a pellet at the bottom. It might be really subtle!',
        },
        {
            shorthand: 'Aspirate media from centrifuge tube',
            stepComplete: false,
            followUpAction: null,
            displayedText: 'Aspirate the media in the 15 mL centrifuge tube carefully. Make sure not to disturb the pellet of cells in the center of the tube.',
            subProtocol: 'TBD',
            spokenPrompt: 'Aspirate the media in the 15 <sub alias=\'milliliters\'>mL</sub> centrifuge tube carefully. Make sure not to disturb the pellet of cells in the center of the tube.',
        },
        {
            shorthand: 'Break up pellet with warmed media',
            stepComplete: false,
            displayedText: 'Add 1 mL of fresh media from the flask that you took out from the incubator to the cell pellet and pipette up and down about 20 times to break up the pellet.',
            subProtocol: 'TBD',
            spokenPrompt: 'Add 1 <sub alias=\'milliliters\'>mL</sub> of fresh media from the flask that you took out from the incubator to the cell pellet and pypette up and down about 20 times to break up the pellet.',
            followUpAction: null,
        },
        {
            shorthand: 'Dilute pellet',
            stepComplete: false,
            displayedText: 'Dilute the cell pellet as you prefer. You should make this decision based on the next day you plan to passage and the starting confluency of your cells. For a 1 to 5 dilution, take 200 µL of the 1 mL. For a 1 to 6 dilution, take 167µL of the 1mL.',
            subProtocol: 'TBD',
            spokenPrompt: 'Dilute the cell pellet as you prefer. You should make this decision based on the next day you plan to passage and the starting confluency of your cells. For a 1 to 5 dilution, take 200 µL of the 1 <sub alias=\'milliliters\'>mL</sub>. For a 1 to 6 dilution, take 167µL of the 1<sub alias=\'milliliters\'>mL</sub>.',
            followUpAction: null,
        },
        {
            shorthand: 'Transfer diluted cells to new flask',
            stepComplete: false,
            subProtocol: 'TBD',
            spokenPrompt: 'Transfer the volume of cells that you decided into your labeled flask with culture media.',
            followUpAction: null,
            displayedText: 'Transfer the volume of cells that you decided into your labeled flask with culture media.',
        },
        {
            shorthand: 'Observe new cell flask',
            stepComplete: false,
            displayedText: 'Observe the cells in the flask under the microscope. You should see the cells floating around in the media.',
            subProtocol: 'TBD',
            spokenPrompt: 'Observe the cells in the flask under the microscope. You should see the cells floating around in the media.',
            followUpAction: null,
        },
        {
            shorthand: 'Put new flask in incubator',
            stepComplete: false,
            displayedText: 'Put your flask into the incubator to allow your cells to grow.',
            subProtocol: 'TBD',
            spokenPrompt: 'Put your flask into the incubator to allow your cells to grow.',
            followUpAction: null,
        },
        {
            shorthand: 'Next steps',
            stepComplete: false,
            subProtocol: 'TBD',
            spokenPrompt: 'Observe the cells under the microscope every day until it\'s time to passage again.',
            followUpAction: null,
            displayedText: 'Observe the cells under the microscope every day until it\'s time to passage again.',
        },
    ],
    currentStep: null,
};

const mutations = {
	MARK_STEP_COMPLETE(state, stepIndex) {
        if ((stepIndex in state.steps) === false) return;
		state.steps[stepIndex].stepComplete = true;
    },
    SET_CURRENT_STEP(state, stepIndex) {
        if ((stepIndex in state.steps) === false) return;
        state.currentStep = stepIndex;
    },
};

const actions = {
	someAsyncTask({ commit }) {
    // do something async
		commit('INCREMENT_MAIN_COUNTER');
        },
};

export default {
    state,
	mutations,
	actions,
};
